<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DocTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [

            // ─── 1. NON-DISCLOSURE AGREEMENT ───────────────────────────────
            [
                'slug'       => 'nda',
                'name'       => 'Non-Disclosure Agreement',
                'short_name' => 'NDA',
                'category'   => 'pre_loi',
                'icon'       => '🔒',
                'description' => 'Mutual or one-way confidentiality agreement to protect sensitive information shared during deal exploration.',
                'sort_order' => 1,
                'variables'  => json_encode([
                    ['key' => 'disclosing_party',       'label' => 'Disclosing Party (Full Legal Name)',    'type' => 'text',   'placeholder' => 'e.g. InvestaFirm Capital LLC',         'required' => true],
                    ['key' => 'receiving_party',         'label' => 'Receiving Party (Full Legal Name)',    'type' => 'text',   'placeholder' => 'e.g. ABC Technologies S.A.E.',          'required' => true],
                    ['key' => 'disclosing_signatory',    'label' => 'Disclosing Party — Signatory Name',   'type' => 'text',   'placeholder' => 'e.g. Mahmoud Youssef',                  'required' => true],
                    ['key' => 'receiving_signatory',     'label' => 'Receiving Party — Signatory Name',    'type' => 'text',   'placeholder' => 'e.g. Ahmed Hassan',                     'required' => true],
                    ['key' => 'disclosing_title',        'label' => 'Disclosing Party — Title',            'type' => 'text',   'placeholder' => 'e.g. Managing Partner',                 'required' => true],
                    ['key' => 'receiving_title',         'label' => 'Receiving Party — Title',             'type' => 'text',   'placeholder' => 'e.g. Chief Executive Officer',          'required' => true],
                    ['key' => 'nda_type',                'label' => 'NDA Type',                            'type' => 'select', 'options' => ['Mutual','One-Way'],                         'required' => true],
                    ['key' => 'purpose',                 'label' => 'Purpose of Disclosure',               'type' => 'textarea','placeholder' => 'e.g. Evaluation of a potential investment in the Company…', 'required' => true],
                    ['key' => 'term_years',              'label' => 'Confidentiality Term (Years)',        'type' => 'number', 'placeholder' => '3',                                     'required' => true],
                    ['key' => 'governing_law',           'label' => 'Governing Law (Country/Jurisdiction)','type' => 'text',   'placeholder' => 'e.g. Arab Republic of Egypt',           'required' => true],
                    ['key' => 'effective_date',          'label' => 'Effective Date',                      'type' => 'date',   'placeholder' => '',                                      'required' => true],
                ]),
            ],

            // ─── 2. LETTER OF INTENT ───────────────────────────────────────
            [
                'slug'       => 'loi',
                'name'       => 'Letter of Intent',
                'short_name' => 'LOI',
                'category'   => 'pre_loi',
                'icon'       => '📋',
                'description' => 'Non-binding (or partially binding) expression of interest outlining key transaction parameters before formal due diligence.',
                'sort_order' => 2,
                'variables'  => json_encode([
                    ['key' => 'investor_name',           'label' => 'Investor / Fund Name',                'type' => 'text',   'placeholder' => 'e.g. SQUAD Capital Partners',           'required' => true],
                    ['key' => 'target_company',          'label' => 'Target Company Name',                 'type' => 'text',   'placeholder' => 'e.g. TechVenture S.A.E.',               'required' => true],
                    ['key' => 'proposed_investment',     'label' => 'Proposed Investment Amount',          'type' => 'text',   'placeholder' => 'e.g. USD 5,000,000',                    'required' => true],
                    ['key' => 'equity_stake',            'label' => 'Target Equity Stake (%)',             'type' => 'text',   'placeholder' => 'e.g. 30%',                              'required' => true],
                    ['key' => 'pre_money_valuation',     'label' => 'Pre-Money Valuation',                 'type' => 'text',   'placeholder' => 'e.g. USD 16,700,000',                   'required' => true],
                    ['key' => 'transaction_structure',   'label' => 'Transaction Structure',               'type' => 'select', 'options' => ['Equity Investment','Convertible Note','Revenue-Based Financing','Mezzanine Debt','Hybrid'], 'required' => true],
                    ['key' => 'use_of_proceeds',         'label' => 'Proposed Use of Proceeds',           'type' => 'textarea','placeholder' => 'e.g. 60% working capital, 30% capex, 10% debt repayment', 'required' => true],
                    ['key' => 'exclusivity_days',        'label' => 'Exclusivity Period (Days)',           'type' => 'number', 'placeholder' => '45',                                    'required' => true],
                    ['key' => 'dd_duration_days',        'label' => 'Due Diligence Duration (Days)',       'type' => 'number', 'placeholder' => '60',                                    'required' => false],
                    ['key' => 'conditions',              'label' => 'Key Conditions Precedent',            'type' => 'textarea','placeholder' => 'e.g. Satisfactory completion of due diligence; regulatory approvals', 'required' => false],
                    ['key' => 'investor_signatory',      'label' => 'Investor Signatory Name',             'type' => 'text',   'placeholder' => 'e.g. Mahmoud Youssef',                  'required' => true],
                    ['key' => 'investor_title',          'label' => 'Investor Signatory Title',            'type' => 'text',   'placeholder' => 'e.g. Founder & Managing Partner',       'required' => true],
                    ['key' => 'effective_date',          'label' => 'Date',                                'type' => 'date',   'placeholder' => '',                                      'required' => true],
                    ['key' => 'governing_law',           'label' => 'Governing Law',                       'type' => 'text',   'placeholder' => 'e.g. Arab Republic of Egypt',           'required' => true],
                ]),
            ],

            // ─── 3. TERM SHEET ─────────────────────────────────────────────
            [
                'slug'       => 'term_sheet',
                'name'       => 'Term Sheet',
                'short_name' => 'Term Sheet',
                'category'   => 'due_diligence',
                'icon'       => '📄',
                'description' => 'Summary of principal terms and conditions for the proposed investment, covering equity, governance, and exit provisions.',
                'sort_order' => 3,
                'variables'  => json_encode([
                    ['key' => 'company_name',            'label' => 'Company Name',                        'type' => 'text',   'placeholder' => 'e.g. TechVenture S.A.E.',               'required' => true],
                    ['key' => 'investor_name',           'label' => 'Investor / Fund Name',                'type' => 'text',   'placeholder' => 'e.g. SQUAD Capital Partners',           'required' => true],
                    ['key' => 'investment_amount',       'label' => 'Investment Amount',                   'type' => 'text',   'placeholder' => 'e.g. USD 5,000,000',                    'required' => true],
                    ['key' => 'pre_money_valuation',     'label' => 'Pre-Money Valuation',                 'type' => 'text',   'placeholder' => 'e.g. USD 16,700,000',                   'required' => true],
                    ['key' => 'equity_percentage',       'label' => 'Equity % (Post-Money)',               'type' => 'text',   'placeholder' => 'e.g. 23.1%',                           'required' => true],
                    ['key' => 'share_class',             'label' => 'Share Class',                         'type' => 'select', 'options' => ['Ordinary Shares','Preference Shares','Class A Ordinary','Class B Ordinary'], 'required' => true],
                    ['key' => 'liquidation_preference',  'label' => 'Liquidation Preference',              'type' => 'select', 'options' => ['1x Non-Participating','1x Participating','2x Non-Participating','None'], 'required' => true],
                    ['key' => 'anti_dilution',           'label' => 'Anti-Dilution Protection',            'type' => 'select', 'options' => ['Broad-Based Weighted Average','Narrow-Based Weighted Average','Full Ratchet','None'], 'required' => true],
                    ['key' => 'board_seats',             'label' => 'Board Seat(s) for Investor',          'type' => 'number', 'placeholder' => '1',                                     'required' => true],
                    ['key' => 'board_total',             'label' => 'Total Board Size',                    'type' => 'number', 'placeholder' => '5',                                     'required' => true],
                    ['key' => 'dividend_policy',         'label' => 'Dividend Policy',                     'type' => 'select', 'options' => ['No dividends until exit','Cumulative preferred dividend','Discretionary by board'], 'required' => true],
                    ['key' => 'tag_along',               'label' => 'Tag-Along Rights',                    'type' => 'select', 'options' => ['Full tag-along','Pro-rata tag-along','None'], 'required' => true],
                    ['key' => 'drag_along',              'label' => 'Drag-Along Rights',                   'type' => 'select', 'options' => ['Yes — investor-triggered at threshold','Yes — majority-triggered','None'], 'required' => true],
                    ['key' => 'rofr',                    'label' => 'Right of First Refusal (ROFR)',       'type' => 'select', 'options' => ['Yes','No'],                                 'required' => true],
                    ['key' => 'pro_rata',                'label' => 'Pro-Rata Rights (Future Rounds)',     'type' => 'select', 'options' => ['Yes','No'],                                 'required' => true],
                    ['key' => 'exit_horizon',            'label' => 'Target Exit Horizon',                 'type' => 'text',   'placeholder' => 'e.g. 5 years from closing',             'required' => false],
                    ['key' => 'vesting_founders',        'label' => 'Founder Vesting Period',              'type' => 'text',   'placeholder' => 'e.g. 4 years with 1-year cliff',        'required' => false],
                    ['key' => 'governing_law',           'label' => 'Governing Law',                       'type' => 'text',   'placeholder' => 'e.g. Arab Republic of Egypt',           'required' => true],
                    ['key' => 'effective_date',          'label' => 'Date',                                'type' => 'date',   'placeholder' => '',                                      'required' => true],
                ]),
            ],

            // ─── 4. SHAREHOLDER AGREEMENT ──────────────────────────────────
            [
                'slug'       => 'sha',
                'name'       => 'Shareholder Agreement',
                'short_name' => 'SHA',
                'category'   => 'closing',
                'icon'       => '🤝',
                'description' => 'Binding agreement governing the rights, obligations, and exit mechanics between shareholders after investment close.',
                'sort_order' => 4,
                'variables'  => json_encode([
                    ['key' => 'company_name',            'label' => 'Company Name',                        'type' => 'text',   'placeholder' => 'e.g. TechVenture S.A.E.',               'required' => true],
                    ['key' => 'company_registration',    'label' => 'Company Registration Number',         'type' => 'text',   'placeholder' => 'e.g. 123456 Cairo',                     'required' => true],
                    ['key' => 'investor_name',           'label' => 'Investor Name',                       'type' => 'text',   'placeholder' => 'e.g. SQUAD Capital Partners',           'required' => true],
                    ['key' => 'investor_equity',         'label' => 'Investor Equity %',                   'type' => 'text',   'placeholder' => 'e.g. 30%',                              'required' => true],
                    ['key' => 'founder_names',           'label' => 'Founder(s) Name(s)',                  'type' => 'textarea','placeholder' => 'e.g. Ahmed Hassan (40%), Sara Mohamed (30%)', 'required' => true],
                    ['key' => 'total_shares',            'label' => 'Total Issued Shares',                 'type' => 'text',   'placeholder' => 'e.g. 10,000,000',                       'required' => true],
                    ['key' => 'share_price',             'label' => 'Price Per Share at Closing',          'type' => 'text',   'placeholder' => 'e.g. USD 1.67',                         'required' => true],
                    ['key' => 'board_composition',       'label' => 'Board Composition',                   'type' => 'textarea','placeholder' => 'e.g. 2 investor-appointed, 2 founder-appointed, 1 independent', 'required' => true],
                    ['key' => 'reserved_matters',        'label' => 'Reserved Matters (Investor Approval Required)', 'type' => 'textarea', 'placeholder' => 'e.g. New share issuance; acquisitions above USD 500k; change of business…', 'required' => false],
                    ['key' => 'dividend_policy',         'label' => 'Dividend Policy',                     'type' => 'textarea','placeholder' => 'e.g. No dividends until investor has achieved 2x MOIC',  'required' => false],
                    ['key' => 'rofr_period_days',        'label' => 'ROFR Exercise Period (Days)',          'type' => 'number', 'placeholder' => '30',                                    'required' => true],
                    ['key' => 'tag_along_threshold',     'label' => 'Tag-Along Trigger (%)',               'type' => 'text',   'placeholder' => 'e.g. 50%+ of shares',                   'required' => false],
                    ['key' => 'drag_along_threshold',    'label' => 'Drag-Along Trigger (%)',              'type' => 'text',   'placeholder' => 'e.g. 75% shareholder approval',          'required' => false],
                    ['key' => 'deadlock_mechanism',      'label' => 'Deadlock Resolution',                 'type' => 'select', 'options' => ['Russian Roulette','Texas Shoot-Out','Independent Expert Determination','Mediation then Arbitration'], 'required' => true],
                    ['key' => 'non_compete_years',       'label' => 'Founder Non-Compete Period (Years)',  'type' => 'number', 'placeholder' => '2',                                     'required' => false],
                    ['key' => 'governing_law',           'label' => 'Governing Law',                       'type' => 'text',   'placeholder' => 'e.g. Arab Republic of Egypt',           'required' => true],
                    ['key' => 'dispute_resolution',      'label' => 'Dispute Resolution',                  'type' => 'select', 'options' => ['Cairo Regional Centre for International Commercial Arbitration (CRCICA)','ICC Arbitration — Paris','Local Courts'], 'required' => true],
                    ['key' => 'effective_date',          'label' => 'Agreement Date',                      'type' => 'date',   'placeholder' => '',                                      'required' => true],
                ]),
            ],

            // ─── 5. OFFERING PROPOSAL / INVESTMENT MEMO ────────────────────
            [
                'slug'       => 'offering_proposal',
                'name'       => 'Offering Proposal',
                'short_name' => 'Proposal',
                'category'   => 'pre_loi',
                'icon'       => '📊',
                'description' => 'Formal investment proposal document to present an opportunity to prospective investors, LPs, or co-investors.',
                'sort_order' => 5,
                'variables'  => json_encode([
                    ['key' => 'company_name',            'label' => 'Company / Opportunity Name',          'type' => 'text',   'placeholder' => 'e.g. TechVenture S.A.E.',               'required' => true],
                    ['key' => 'presenter_firm',          'label' => 'Presenting Firm',                     'type' => 'text',   'placeholder' => 'e.g. SQUAD Financial Consulting',       'required' => true],
                    ['key' => 'sector',                  'label' => 'Sector / Industry',                   'type' => 'text',   'placeholder' => 'e.g. FinTech / B2B SaaS',               'required' => true],
                    ['key' => 'geography',               'label' => 'Geography',                           'type' => 'text',   'placeholder' => 'e.g. Egypt & MENA',                     'required' => true],
                    ['key' => 'investment_ask',          'label' => 'Investment Ask',                      'type' => 'text',   'placeholder' => 'e.g. USD 5,000,000 for 30% equity',     'required' => true],
                    ['key' => 'valuation',               'label' => 'Pre-Money Valuation',                 'type' => 'text',   'placeholder' => 'e.g. USD 16.7M',                        'required' => true],
                    ['key' => 'revenue_ttm',             'label' => 'Revenue (TTM)',                       'type' => 'text',   'placeholder' => 'e.g. EGP 85M',                          'required' => false],
                    ['key' => 'ebitda_ttm',              'label' => 'EBITDA (TTM)',                        'type' => 'text',   'placeholder' => 'e.g. EGP 18M',                          'required' => false],
                    ['key' => 'use_of_funds',            'label' => 'Use of Funds',                        'type' => 'textarea','placeholder' => 'e.g. 60% working capital, 30% CAPEX expansion, 10% debt repayment', 'required' => true],
                    ['key' => 'investment_highlights',   'label' => 'Key Investment Highlights',           'type' => 'textarea','placeholder' => 'Bullet-point highlights: market leadership, recurring revenue, etc.', 'required' => true],
                    ['key' => 'market_size',             'label' => 'Total Addressable Market',            'type' => 'text',   'placeholder' => 'e.g. USD 2.4B by 2027',                 'required' => false],
                    ['key' => 'competitive_advantage',   'label' => 'Competitive Advantage / Moat',       'type' => 'textarea','placeholder' => 'e.g. Proprietary technology, 5-year exclusive distribution rights…', 'required' => false],
                    ['key' => 'risk_factors',            'label' => 'Key Risk Factors',                   'type' => 'textarea','placeholder' => 'e.g. FX risk, regulatory environment, key-person dependency', 'required' => false],
                    ['key' => 'exit_strategy',           'label' => 'Exit Strategy',                       'type' => 'textarea','placeholder' => 'e.g. Strategic sale in year 5; IPO on EGX', 'required' => false],
                    ['key' => 'contact_person',          'label' => 'Contact Person',                      'type' => 'text',   'placeholder' => 'e.g. Mahmoud Youssef',                  'required' => true],
                    ['key' => 'contact_email',           'label' => 'Contact Email',                       'type' => 'text',   'placeholder' => 'e.g. mahmoud@squad.com',                'required' => true],
                    ['key' => 'document_date',           'label' => 'Document Date',                       'type' => 'date',   'placeholder' => '',                                      'required' => true],
                    ['key' => 'confidentiality_note',    'label' => 'Confidentiality Footer Note',         'type' => 'textarea','placeholder' => 'e.g. This document is strictly confidential and intended solely for the named recipient.', 'required' => false],
                ]),
            ],

            // ─── 6. SUBSCRIPTION AGREEMENT ────────────────────────────────
            [
                'slug'       => 'subscription_agreement',
                'name'       => 'Subscription Agreement',
                'short_name' => 'Sub. Agreement',
                'category'   => 'closing',
                'icon'       => '✍️',
                'description' => 'Binding agreement through which an investor formally subscribes for new shares in a company at closing.',
                'sort_order' => 6,
                'variables'  => json_encode([
                    ['key' => 'company_name',            'label' => 'Company Name',                        'type' => 'text',   'placeholder' => 'e.g. TechVenture S.A.E.',               'required' => true],
                    ['key' => 'company_address',         'label' => 'Company Registered Address',          'type' => 'textarea','placeholder' => 'e.g. 10 El Tahrir Square, Cairo, Egypt', 'required' => true],
                    ['key' => 'investor_name',           'label' => 'Investor Full Legal Name',            'type' => 'text',   'placeholder' => 'e.g. SQUAD Capital Partners LLC',       'required' => true],
                    ['key' => 'investor_address',        'label' => 'Investor Registered Address',         'type' => 'textarea','placeholder' => 'e.g. 5 Mossadak St, Dokki, Giza',      'required' => true],
                    ['key' => 'shares_subscribed',       'label' => 'Number of Shares Subscribed',         'type' => 'text',   'placeholder' => 'e.g. 3,000,000',                        'required' => true],
                    ['key' => 'price_per_share',         'label' => 'Price Per Share',                     'type' => 'text',   'placeholder' => 'e.g. USD 1.67',                         'required' => true],
                    ['key' => 'total_subscription',      'label' => 'Total Subscription Amount',           'type' => 'text',   'placeholder' => 'e.g. USD 5,010,000',                    'required' => true],
                    ['key' => 'currency',                'label' => 'Currency',                            'type' => 'select', 'options' => ['USD','EUR','GBP','EGP','AED','SAR'],        'required' => true],
                    ['key' => 'payment_account',         'label' => 'Payment Bank Account Details',        'type' => 'textarea','placeholder' => 'Bank name, IBAN, Swift/BIC',           'required' => true],
                    ['key' => 'payment_deadline_days',   'label' => 'Payment Deadline (Days from Signing)','type' => 'number', 'placeholder' => '5',                                     'required' => true],
                    ['key' => 'share_class',             'label' => 'Share Class',                         'type' => 'select', 'options' => ['Ordinary Shares','Class A Preference Shares','Class B Ordinary'], 'required' => true],
                    ['key' => 'closing_conditions',      'label' => 'Conditions to Closing',               'type' => 'textarea','placeholder' => 'e.g. Board approval; regulatory filing; cap table update', 'required' => false],
                    ['key' => 'rep_warranties',          'label' => 'Key Representations & Warranties',    'type' => 'textarea','placeholder' => 'e.g. No undisclosed liabilities; shares free of encumbrance', 'required' => false],
                    ['key' => 'company_signatory',       'label' => 'Company Signatory Name',              'type' => 'text',   'placeholder' => 'e.g. Ahmed Hassan',                     'required' => true],
                    ['key' => 'company_signatory_title', 'label' => 'Company Signatory Title',             'type' => 'text',   'placeholder' => 'e.g. Chief Executive Officer',          'required' => true],
                    ['key' => 'investor_signatory',      'label' => 'Investor Signatory Name',             'type' => 'text',   'placeholder' => 'e.g. Mahmoud Youssef',                  'required' => true],
                    ['key' => 'investor_signatory_title','label' => 'Investor Signatory Title',            'type' => 'text',   'placeholder' => 'e.g. Managing Partner',                 'required' => true],
                    ['key' => 'governing_law',           'label' => 'Governing Law',                       'type' => 'text',   'placeholder' => 'e.g. Arab Republic of Egypt',           'required' => true],
                    ['key' => 'effective_date',          'label' => 'Agreement Date',                      'type' => 'date',   'placeholder' => '',                                      'required' => true],
                ]),
            ],

            // ─── 7. TEASER / ONE-PAGER ───────────────────────────────────────────────────
[
    'slug'        => 'teaser',
    'name'        => 'Teaser / One-Pager',
    'short_name'  => 'Teaser',
    'category'    => 'pre_loi',
    'icon'        => '📄',
    'description' => '1-page blind summary sent before NDA to spark investor interest — no sensitive data disclosed.',
    'sort_order'  => 7,
    'variables'   => json_encode([
        ['key' => 'opportunity_codename',   'label' => 'Opportunity Code Name (Blind)',        'type' => 'text',    'placeholder' => 'e.g. Project Falcon',                    'required' => true],
        ['key' => 'sector',                 'label' => 'Sector / Industry',                    'type' => 'text',    'placeholder' => 'e.g. Healthcare Technology',             'required' => true],
        ['key' => 'geography',              'label' => 'Geography / Market',                   'type' => 'text',    'placeholder' => 'e.g. Egypt & East Africa',               'required' => true],
        ['key' => 'business_description',   'label' => 'Business Description (2–3 sentences)', 'type' => 'textarea','placeholder' => 'What the company does, its model, and key customers — without revealing identity.', 'required' => true],
        ['key' => 'investment_ask',         'label' => 'Investment Ask',                       'type' => 'text',    'placeholder' => 'e.g. USD 4–6M for 25–35% equity',        'required' => true],
        ['key' => 'revenue_ttm',            'label' => 'Revenue (TTM, indicative)',             'type' => 'text',    'placeholder' => 'e.g. ~EGP 120M',                         'required' => false],
        ['key' => 'ebitda_ttm',             'label' => 'EBITDA (TTM, indicative)',              'type' => 'text',    'placeholder' => 'e.g. ~EGP 28M',                          'required' => false],
        ['key' => 'growth_cagr',            'label' => 'Revenue Growth (CAGR or YoY %)',       'type' => 'text',    'placeholder' => 'e.g. 42% YoY',                           'required' => false],
        ['key' => 'key_highlights',         'label' => 'Top 3–5 Investment Highlights',        'type' => 'textarea','placeholder' => "• Market leader in niche\n• Recurring revenue model\n• Strong management team", 'required' => true],
        ['key' => 'exit_outlook',           'label' => 'Exit Outlook (1–2 sentences)',          'type' => 'textarea','placeholder' => 'e.g. Strategic trade sale or regional PE secondary in years 4–6.', 'required' => false],
        ['key' => 'contact_person',         'label' => 'Contact Person',                       'type' => 'text',    'placeholder' => 'e.g. Mahmoud Youssef',                   'required' => true],
        ['key' => 'contact_email',          'label' => 'Contact Email',                        'type' => 'text',    'placeholder' => 'e.g. mahmoud@squad.com',                 'required' => true],
        ['key' => 'contact_phone',          'label' => 'Contact Phone / WhatsApp',             'type' => 'text',    'placeholder' => 'e.g. +20 100 000 0000',                  'required' => false],
        ['key' => 'document_date',          'label' => 'Document Date',                        'type' => 'date',    'placeholder' => '',                                       'required' => true],
        ['key' => 'confidentiality_note',   'label' => 'Confidentiality Footer',               'type' => 'textarea','placeholder' => 'This document is strictly confidential and for discussion purposes only.', 'required' => false],
    ]),
],

// ─── 8. INFORMATION MEMORANDUM ───────────────────────────────────────────────
[
    'slug'        => 'information_memorandum',
    'name'        => 'Information Memorandum',
    'short_name'  => 'IM',
    'category'    => 'pre_loi',
    'icon'        => '📘',
    'description' => 'Full detailed company overview sent post-NDA — the primary deal marketing document.',
    'sort_order'  => 8,
    'variables'   => json_encode([
        ['key' => 'company_name',           'label' => 'Company Full Legal Name',              'type' => 'text',    'placeholder' => 'e.g. TechVenture S.A.E.',                'required' => true],
        ['key' => 'company_address',        'label' => 'Registered Address',                   'type' => 'textarea','placeholder' => 'e.g. 10 El Tahrir Square, Cairo, Egypt', 'required' => true],
        ['key' => 'founded_year',           'label' => 'Year Founded',                         'type' => 'text',    'placeholder' => 'e.g. 2018',                              'required' => true],
        ['key' => 'legal_structure',        'label' => 'Legal Structure',                      'type' => 'select',  'options' => ['S.A.E.','LLC','JSC','LLP','Other'],          'required' => true],
        ['key' => 'sector',                 'label' => 'Sector / Sub-sector',                  'type' => 'text',    'placeholder' => 'e.g. B2B SaaS / ERP for SMEs',           'required' => true],
        ['key' => 'geography',              'label' => 'Geographic Footprint',                 'type' => 'text',    'placeholder' => 'e.g. Egypt, UAE, Saudi Arabia',          'required' => true],
        ['key' => 'business_overview',      'label' => 'Business Overview (3–5 sentences)',    'type' => 'textarea','placeholder' => 'Company history, mission, core products/services, and market position.', 'required' => true],
        ['key' => 'products_services',      'label' => 'Products & Services',                  'type' => 'textarea','placeholder' => 'List main products/services with brief descriptions.', 'required' => true],
        ['key' => 'revenue_model',          'label' => 'Revenue Model',                        'type' => 'textarea','placeholder' => 'e.g. SaaS subscriptions (80%), professional services (20%)', 'required' => true],
        ['key' => 'customer_base',          'label' => 'Customer Base',                        'type' => 'textarea','placeholder' => 'Number of customers, top clients (by %), concentration risk.', 'required' => false],
        ['key' => 'management_team',        'label' => 'Management Team',                      'type' => 'textarea','placeholder' => "CEO — Ahmed Hassan, 15 yrs exp\nCFO — Sara Khalil, ex-EY", 'required' => true],
        ['key' => 'financials_summary',     'label' => 'Financial Highlights (3 years)',       'type' => 'textarea','placeholder' => "FY2022: Revenue EGP 60M, EBITDA EGP 12M\nFY2023: Revenue EGP 90M, EBITDA EGP 20M\nFY2024: Revenue EGP 130M, EBITDA EGP 31M", 'required' => true],
        ['key' => 'investment_ask',         'label' => 'Investment Ask',                       'type' => 'text',    'placeholder' => 'e.g. USD 6M for 30% equity',             'required' => true],
        ['key' => 'use_of_proceeds',        'label' => 'Use of Proceeds',                      'type' => 'textarea','placeholder' => "60% expansion capex\n30% working capital\n10% debt paydown", 'required' => true],
        ['key' => 'growth_strategy',        'label' => 'Growth Strategy',                      'type' => 'textarea','placeholder' => 'Geographic expansion, new product lines, M&A bolt-ons, etc.', 'required' => false],
        ['key' => 'competitive_landscape',  'label' => 'Competitive Landscape',                'type' => 'textarea','placeholder' => 'Main competitors and differentiation.', 'required' => false],
        ['key' => 'key_risks',              'label' => 'Key Risks & Mitigants',                'type' => 'textarea','placeholder' => "Risk: FX volatility\nMitigant: USD-denominated contracts", 'required' => false],
        ['key' => 'exit_strategy',          'label' => 'Exit Strategy & Timeline',             'type' => 'textarea','placeholder' => 'e.g. Strategic sale in Year 5; IPO consideration.', 'required' => false],
        ['key' => 'prepared_by',            'label' => 'Prepared By (Firm)',                   'type' => 'text',    'placeholder' => 'e.g. SQUAD Financial Consulting',        'required' => true],
        ['key' => 'contact_person',         'label' => 'Contact Person',                       'type' => 'text',    'placeholder' => 'e.g. Mahmoud Youssef',                   'required' => true],
        ['key' => 'contact_email',          'label' => 'Contact Email',                        'type' => 'text',    'placeholder' => 'e.g. mahmoud@squad.com',                 'required' => true],
        ['key' => 'document_date',          'label' => 'Document Date',                        'type' => 'date',    'placeholder' => '',                                       'required' => true],
        ['key' => 'confidentiality_note',   'label' => 'Confidentiality Footer',               'type' => 'textarea','placeholder' => 'Strictly confidential. Prepared solely for the named recipient post-NDA.', 'required' => false],
    ]),
],

// ─── 9. MANAGEMENT PRESENTATION TEMPLATE ─────────────────────────────────────
[
    'slug'        => 'management_presentation',
    'name'        => 'Management Presentation Template',
    'short_name'  => 'Mgmt Deck',
    'category'    => 'pre_loi',
    'icon'        => '🎤',
    'description' => 'Structured outline for the founder/management team pitch to investors — covers company, market, financials, and ask.',
    'sort_order'  => 9,
    'variables'   => json_encode([
        ['key' => 'company_name',           'label' => 'Company Name',                         'type' => 'text',    'placeholder' => 'e.g. TechVenture S.A.E.',                'required' => true],
        ['key' => 'presentation_date',      'label' => 'Presentation Date',                    'type' => 'date',    'placeholder' => '',                                       'required' => true],
        ['key' => 'presenter_names',        'label' => 'Presenters (Name & Title)',             'type' => 'textarea','placeholder' => "Ahmed Hassan — CEO\nSara Khalil — CFO",  'required' => true],
        ['key' => 'investor_audience',      'label' => 'Investor Audience (Fund / Firm Name)', 'type' => 'text',    'placeholder' => 'e.g. SQUAD Capital Partners',            'required' => true],
        ['key' => 'company_tagline',        'label' => 'Company Tagline / One-Liner',          'type' => 'text',    'placeholder' => 'e.g. The ERP platform built for MENA SMEs', 'required' => true],
        ['key' => 'problem_statement',      'label' => 'Problem Being Solved',                 'type' => 'textarea','placeholder' => 'What pain point exists in the market today?', 'required' => true],
        ['key' => 'solution',               'label' => 'The Solution',                         'type' => 'textarea','placeholder' => 'How does the company solve this problem?', 'required' => true],
        ['key' => 'market_size',            'label' => 'Total Addressable Market (TAM)',       'type' => 'text',    'placeholder' => 'e.g. USD 2.4B by 2027 (MENA ERP market)', 'required' => false],
        ['key' => 'business_model',         'label' => 'Business Model Summary',               'type' => 'textarea','placeholder' => 'How the company makes money — pricing, channels, retention.', 'required' => true],
        ['key' => 'traction',               'label' => 'Key Traction / Milestones',            'type' => 'textarea','placeholder' => "• 180 enterprise clients\n• EGP 130M revenue FY2024\n• 94% renewal rate", 'required' => true],
        ['key' => 'competitive_advantage',  'label' => 'Competitive Advantage',                'type' => 'textarea','placeholder' => 'Moat, IP, partnerships, exclusive contracts, etc.', 'required' => false],
        ['key' => 'financial_snapshot',     'label' => 'Financial Snapshot (3 years)',         'type' => 'textarea','placeholder' => "FY2022: Rev EGP 60M | EBITDA EGP 12M\nFY2023: Rev EGP 90M | EBITDA EGP 20M\nFY2024: Rev EGP 130M | EBITDA EGP 31M", 'required' => true],
        ['key' => 'investment_ask',         'label' => 'Investment Ask & Use of Funds',        'type' => 'textarea','placeholder' => "Raising USD 6M for 30% equity\n• 60% CAPEX\n• 30% Working Capital\n• 10% Debt", 'required' => true],
        ['key' => 'exit_strategy',          'label' => 'Exit Strategy',                        'type' => 'textarea','placeholder' => 'Strategic trade sale, secondary, or IPO — expected timeline.', 'required' => false],
        ['key' => 'contact_email',          'label' => 'Contact Email',                        'type' => 'text',    'placeholder' => 'e.g. ahmed@techventure.com',             'required' => true],
        ['key' => 'confidentiality_note',   'label' => 'Confidentiality Footer',               'type' => 'textarea','placeholder' => 'Confidential. Not for distribution without prior written consent.', 'required' => false],
    ]),
],

// ─────────────────────────────────────────────────────────────────────────────
// DUE DILIGENCE
// ─────────────────────────────────────────────────────────────────────────────

// ─── 10. DUE DILIGENCE REQUEST LIST ──────────────────────────────────────────
[
    'slug'        => 'dd_request_list',
    'name'        => 'Due Diligence Request List',
    'short_name'  => 'DD Request',
    'category'    => 'due_diligence',
    'icon'        => '🗂️',
    'description' => 'Comprehensive checklist of all documents and information requested from the target company.',
    'sort_order'  => 10,
    'variables'   => json_encode([
        ['key' => 'investor_name',          'label' => 'Investor / Fund Name',                 'type' => 'text',    'placeholder' => 'e.g. SQUAD Capital Partners',            'required' => true],
        ['key' => 'target_company',         'label' => 'Target Company Name',                  'type' => 'text',    'placeholder' => 'e.g. TechVenture S.A.E.',                'required' => true],
        ['key' => 'dd_coordinator_investor','label' => 'DD Coordinator — Investor Side',       'type' => 'text',    'placeholder' => 'e.g. Mahmoud Youssef, mahmoud@squad.com','required' => true],
        ['key' => 'dd_coordinator_target',  'label' => 'DD Coordinator — Target Side',         'type' => 'text',    'placeholder' => 'e.g. Sara Khalil, cfo@techventure.com',  'required' => true],
        ['key' => 'submission_deadline',    'label' => 'Document Submission Deadline',         'type' => 'date',    'placeholder' => '',                                       'required' => true],
        ['key' => 'data_room_platform',     'label' => 'Data Room Platform',                   'type' => 'text',    'placeholder' => 'e.g. InvestaWatch Data Room / Dropbox / Datasite', 'required' => false],
        ['key' => 'dd_scope',               'label' => 'DD Scope',                             'type' => 'select',  'options' => ['Full (Financial + Legal + Commercial + Technical)','Financial & Legal Only','Commercial Only','Financial Only'], 'required' => true],
        ['key' => 'financial_years',        'label' => 'Financial Periods Required',           'type' => 'text',    'placeholder' => 'e.g. FY2022, FY2023, FY2024 + YTD 2025', 'required' => true],
        ['key' => 'additional_requests',    'label' => 'Additional / Custom Requests',         'type' => 'textarea','placeholder' => 'Any deal-specific items beyond the standard checklist.', 'required' => false],
        ['key' => 'governing_law',          'label' => 'Governing Law',                        'type' => 'text',    'placeholder' => 'e.g. Arab Republic of Egypt',            'required' => false],
        ['key' => 'document_date',          'label' => 'Document Date',                        'type' => 'date',    'placeholder' => '',                                       'required' => true],
    ]),
],

// ─── 11. DUE DILIGENCE SUMMARY REPORT ────────────────────────────────────────
[
    'slug'        => 'dd_summary_report',
    'name'        => 'Due Diligence Summary Report',
    'short_name'  => 'DD Report',
    'category'    => 'due_diligence',
    'icon'        => '🔎',
    'description' => 'Findings summary across financial, legal, and commercial workstreams — presented to the investment committee.',
    'sort_order'  => 11,
    'variables'   => json_encode([
        ['key' => 'target_company',         'label' => 'Target Company Name',                  'type' => 'text',    'placeholder' => 'e.g. TechVenture S.A.E.',                'required' => true],
        ['key' => 'investor_name',          'label' => 'Investor / Fund Name',                 'type' => 'text',    'placeholder' => 'e.g. SQUAD Capital Partners',            'required' => true],
        ['key' => 'dd_period',              'label' => 'DD Period (From – To)',                 'type' => 'text',    'placeholder' => 'e.g. 1 Dec 2024 – 15 Jan 2025',          'required' => true],
        ['key' => 'prepared_by',            'label' => 'Report Prepared By',                   'type' => 'text',    'placeholder' => 'e.g. SQUAD Financial Consulting',        'required' => true],
        ['key' => 'overall_recommendation', 'label' => 'Overall Recommendation',               'type' => 'select',  'options' => ['Proceed — No Material Issues','Proceed — Subject to Conditions','Requires Further Investigation','Do Not Proceed'], 'required' => true],
        ['key' => 'executive_summary',      'label' => 'Executive Summary',                    'type' => 'textarea','placeholder' => '3–5 sentence overall assessment for IC.','required' => true],
        ['key' => 'financial_findings',     'label' => 'Financial DD Findings',                'type' => 'textarea','placeholder' => "Revenue quality, EBITDA sustainability, working capital, debt levels, off-balance sheet items…", 'required' => true],
        ['key' => 'legal_findings',         'label' => 'Legal DD Findings',                    'type' => 'textarea','placeholder' => "Corporate structure, litigation, IP ownership, key contracts, regulatory compliance…", 'required' => true],
        ['key' => 'commercial_findings',    'label' => 'Commercial DD Findings',               'type' => 'textarea','placeholder' => "Market position, customer concentration, competitive threats, pipeline quality…", 'required' => false],
        ['key' => 'red_flags',              'label' => 'Red Flags / Deal-Breakers',            'type' => 'textarea','placeholder' => 'Any issues that could affect valuation or the decision to proceed.', 'required' => false],
        ['key' => 'conditions_to_close',    'label' => 'Conditions to Close / Reps Required',  'type' => 'textarea','placeholder' => 'Remediation items the target must address before signing.', 'required' => false],
        ['key' => 'valuation_impact',       'label' => 'Valuation Adjustments (if any)',       'type' => 'textarea','placeholder' => 'e.g. EBITDA adjusted down by EGP 3M for one-off items.', 'required' => false],
        ['key' => 'document_date',          'label' => 'Report Date',                          'type' => 'date',    'placeholder' => '',                                       'required' => true],
    ]),
],

// ─── 12. DATA ROOM ACCESS LETTER ─────────────────────────────────────────────
[
    'slug'        => 'data_room_access_letter',
    'name'        => 'Data Room Access Letter',
    'short_name'  => 'DR Access',
    'category'    => 'due_diligence',
    'icon'        => '🔐',
    'description' => 'Formal letter granting a named party controlled access to the virtual data room.',
    'sort_order'  => 12,
    'variables'   => json_encode([
        ['key' => 'issuing_company',        'label' => 'Issuing Company (Granting Access)',    'type' => 'text',    'placeholder' => 'e.g. TechVenture S.A.E.',                'required' => true],
        ['key' => 'issuing_signatory',      'label' => 'Issuing Signatory Name & Title',       'type' => 'text',    'placeholder' => 'e.g. Ahmed Hassan, CEO',                 'required' => true],
        ['key' => 'recipient_firm',         'label' => 'Recipient Firm / Fund',                'type' => 'text',    'placeholder' => 'e.g. SQUAD Capital Partners',            'required' => true],
        ['key' => 'authorized_users',       'label' => 'Authorized Users (Names & Emails)',    'type' => 'textarea','placeholder' => "Mahmoud Youssef — mahmoud@squad.com\nSara Ali — sara@squad.com", 'required' => true],
        ['key' => 'data_room_platform',     'label' => 'Data Room Platform & Link',            'type' => 'text',    'placeholder' => 'e.g. InvestaWatch Data Room — https://investawatch.test/…', 'required' => true],
        ['key' => 'access_level',           'label' => 'Access Level',                         'type' => 'select',  'options' => ['Full Access','Financial Section Only','Legal Section Only','View-Only (No Download)'], 'required' => true],
        ['key' => 'access_start_date',      'label' => 'Access Start Date',                    'type' => 'date',    'placeholder' => '',                                       'required' => true],
        ['key' => 'access_expiry_date',     'label' => 'Access Expiry Date',                   'type' => 'date',    'placeholder' => '',                                       'required' => true],
        ['key' => 'nda_reference',          'label' => 'Reference NDA / Confidentiality Agreement', 'type' => 'text','placeholder' => 'e.g. NDA dated 1 December 2024',        'required' => true],
        ['key' => 'restrictions',           'label' => 'Usage Restrictions',                   'type' => 'textarea','placeholder' => 'No printing, forwarding, or sharing outside authorized users.', 'required' => false],
        ['key' => 'contact_for_queries',    'label' => 'Contact for DD Queries',               'type' => 'text',    'placeholder' => 'e.g. Sara Khalil — cfo@techventure.com', 'required' => true],
        ['key' => 'letter_date',            'label' => 'Letter Date',                          'type' => 'date',    'placeholder' => '',                                       'required' => true],
        ['key' => 'governing_law',          'label' => 'Governing Law',                        'type' => 'text',    'placeholder' => 'e.g. Arab Republic of Egypt',            'required' => false],
    ]),
],

// ─────────────────────────────────────────────────────────────────────────────
// VALUATION & NEGOTIATION
// ─────────────────────────────────────────────────────────────────────────────

// ─── 13. VALUATION SUMMARY ───────────────────────────────────────────────────
[
    'slug'        => 'valuation_summary',
    'name'        => 'Valuation Summary',
    'short_name'  => 'Valuation',
    'category'    => 'valuation',
    'icon'        => '💹',
    'description' => 'Summary of EBITDA multiples, DCF, and comparable transaction analysis — supports price negotiation.',
    'sort_order'  => 13,
    'variables'   => json_encode([
        ['key' => 'target_company',         'label' => 'Target Company Name',                  'type' => 'text',    'placeholder' => 'e.g. TechVenture S.A.E.',                'required' => true],
        ['key' => 'valuation_date',         'label' => 'Valuation Date',                       'type' => 'date',    'placeholder' => '',                                       'required' => true],
        ['key' => 'prepared_by',            'label' => 'Prepared By',                          'type' => 'text',    'placeholder' => 'e.g. SQUAD Financial Consulting',        'required' => true],
        ['key' => 'currency',               'label' => 'Reporting Currency',                   'type' => 'select',  'options' => ['USD','EUR','GBP','EGP','AED','SAR'],         'required' => true],
        ['key' => 'ltm_ebitda',             'label' => 'LTM EBITDA',                           'type' => 'text',    'placeholder' => 'e.g. EGP 31,000,000',                    'required' => true],
        ['key' => 'ebitda_multiple_low',    'label' => 'EBITDA Multiple Range — Low',          'type' => 'text',    'placeholder' => 'e.g. 5.0x',                              'required' => true],
        ['key' => 'ebitda_multiple_high',   'label' => 'EBITDA Multiple Range — High',         'type' => 'text',    'placeholder' => 'e.g. 7.0x',                              'required' => true],
        ['key' => 'ebitda_implied_low',     'label' => 'Implied Enterprise Value — Low',       'type' => 'text',    'placeholder' => 'e.g. EGP 155M',                          'required' => false],
        ['key' => 'ebitda_implied_high',    'label' => 'Implied Enterprise Value — High',      'type' => 'text',    'placeholder' => 'e.g. EGP 217M',                          'required' => false],
        ['key' => 'dcf_wacc',               'label' => 'DCF — WACC (%)',                       'type' => 'text',    'placeholder' => 'e.g. 18%',                               'required' => false],
        ['key' => 'dcf_terminal_growth',    'label' => 'DCF — Terminal Growth Rate (%)',       'type' => 'text',    'placeholder' => 'e.g. 3%',                                'required' => false],
        ['key' => 'dcf_enterprise_value',   'label' => 'DCF — Enterprise Value',               'type' => 'text',    'placeholder' => 'e.g. EGP 185M',                          'required' => false],
        ['key' => 'comparable_transactions','label' => 'Comparable Transactions (Comps)',      'type' => 'textarea','placeholder' => "Company A — 6.2x EV/EBITDA (2023)\nCompany B — 5.8x EV/EBITDA (2024)", 'required' => false],
        ['key' => 'net_debt',               'label' => 'Net Debt (to derive Equity Value)',    'type' => 'text',    'placeholder' => 'e.g. EGP (20M) — net cash position',     'required' => false],
        ['key' => 'concluded_ev',           'label' => 'Concluded Enterprise Value',           'type' => 'text',    'placeholder' => 'e.g. EGP 190M',                          'required' => true],
        ['key' => 'concluded_equity_value',  'label' => 'Concluded Equity Value',              'type' => 'text',    'placeholder' => 'e.g. EGP 210M',                          'required' => true],
        ['key' => 'proposed_stake',         'label' => 'Proposed Stake (%)',                   'type' => 'text',    'placeholder' => 'e.g. 30%',                               'required' => true],
        ['key' => 'investment_amount',      'label' => 'Investment Amount',                    'type' => 'text',    'placeholder' => 'e.g. EGP 63M (≈ USD 1.3M)',              'required' => true],
        ['key' => 'key_assumptions',        'label' => 'Key Valuation Assumptions',            'type' => 'textarea','placeholder' => 'Revenue CAGR, EBITDA margin expansion, capex assumptions, exit year.', 'required' => false],
        ['key' => 'sensitivity_note',       'label' => 'Sensitivity Notes',                    'type' => 'textarea','placeholder' => 'Range of outcomes under bear / base / bull scenarios.', 'required' => false],
    ]),
],

// ─── 14. INDICATIVE OFFER LETTER ─────────────────────────────────────────────
[
    'slug'        => 'indicative_offer_letter',
    'name'        => 'Indicative Offer Letter',
    'short_name'  => 'Offer Letter',
    'category'    => 'valuation',
    'icon'        => '💌',
    'description' => 'Softer than an LOI — used for early price anchoring and to signal serious interest before formal process.',
    'sort_order'  => 14,
    'variables'   => json_encode([
        ['key' => 'investor_name',          'label' => 'Investor / Fund Name',                 'type' => 'text',    'placeholder' => 'e.g. SQUAD Capital Partners',            'required' => true],
        ['key' => 'investor_address',       'label' => 'Investor Address',                     'type' => 'textarea','placeholder' => 'e.g. 5 Mossadak St, Dokki, Giza, Egypt', 'required' => true],
        ['key' => 'target_company',         'label' => 'Target Company Name',                  'type' => 'text',    'placeholder' => 'e.g. TechVenture S.A.E.',                'required' => true],
        ['key' => 'recipient_name',         'label' => 'Recipient Name & Title',               'type' => 'text',    'placeholder' => 'e.g. Ahmed Hassan, CEO',                 'required' => true],
        ['key' => 'indicative_valuation',   'label' => 'Indicative Enterprise Value',          'type' => 'text',    'placeholder' => 'e.g. USD 12M – 15M',                     'required' => true],
        ['key' => 'indicative_stake',       'label' => 'Indicative Stake (%)',                 'type' => 'text',    'placeholder' => 'e.g. 25% – 35%',                         'required' => true],
        ['key' => 'indicative_investment',  'label' => 'Indicative Investment Amount',         'type' => 'text',    'placeholder' => 'e.g. USD 3.5M – 5M',                     'required' => true],
        ['key' => 'transaction_structure',  'label' => 'Proposed Structure',                   'type' => 'select',  'options' => ['Primary Equity','Secondary Equity','Primary + Secondary','Convertible Note','Mezzanine'], 'required' => true],
        ['key' => 'basis_of_offer',         'label' => 'Basis of Offer',                       'type' => 'textarea','placeholder' => 'Valuation methodology used — multiples, DCF, precedent transactions.', 'required' => true],
        ['key' => 'key_conditions',         'label' => 'Key Conditions',                       'type' => 'textarea','placeholder' => "• Satisfactory DD\n• No material adverse change\n• Regulatory approval", 'required' => true],
        ['key' => 'next_steps',             'label' => 'Proposed Next Steps',                  'type' => 'textarea','placeholder' => "1. Mutual acceptance of this letter\n2. Execute NDA\n3. Share DD request list", 'required' => false],
        ['key' => 'offer_validity_days',    'label' => 'Offer Validity (Days)',                 'type' => 'number',  'placeholder' => '14',                                     'required' => true],
        ['key' => 'investor_signatory',     'label' => 'Investor Signatory Name',              'type' => 'text',    'placeholder' => 'e.g. Mahmoud Youssef',                   'required' => true],
        ['key' => 'investor_title',         'label' => 'Investor Signatory Title',             'type' => 'text',    'placeholder' => 'e.g. Founder & Managing Partner',        'required' => true],
        ['key' => 'letter_date',            'label' => 'Letter Date',                          'type' => 'date',    'placeholder' => '',                                       'required' => true],
        ['key' => 'governing_law',          'label' => 'Governing Law',                        'type' => 'text',    'placeholder' => 'e.g. Arab Republic of Egypt',            'required' => false],
    ]),
],

// ─────────────────────────────────────────────────────────────────────────────
// CLOSING
// ─────────────────────────────────────────────────────────────────────────────

// ─── 15. BOARD RESOLUTION ────────────────────────────────────────────────────
[
    'slug'        => 'board_resolution',
    'name'        => 'Board Resolution',
    'short_name'  => 'Board Resolution',
    'category'    => 'closing',
    'icon'        => '🏛️',
    'description' => 'Formal board resolution approving the investment transaction — required by most jurisdictions at closing.',
    'sort_order'  => 15,
    'variables'   => json_encode([
        ['key' => 'company_name',           'label' => 'Company Name (Board Issuing Resolution)', 'type' => 'text', 'placeholder' => 'e.g. TechVenture S.A.E.',               'required' => true],
        ['key' => 'company_registration',   'label' => 'Company Registration / Commercial No.',  'type' => 'text',  'placeholder' => 'e.g. 12345 Cairo Commercial Registry',  'required' => false],
        ['key' => 'meeting_type',           'label' => 'Meeting Type',                           'type' => 'select','options' => ['Board of Directors Meeting','Extraordinary General Meeting','Written Consent Resolution'], 'required' => true],
        ['key' => 'meeting_date',           'label' => 'Meeting Date',                           'type' => 'date',  'placeholder' => '',                                      'required' => true],
        ['key' => 'meeting_location',       'label' => 'Meeting Location',                       'type' => 'text',  'placeholder' => 'e.g. Company HQ, Cairo / Via Video Conference', 'required' => true],
        ['key' => 'quorum_present',         'label' => 'Directors Present (Names)',              'type' => 'textarea','placeholder' => "Ahmed Hassan (Chairman)\nSara Khalil\nOmar Nour", 'required' => true],
        ['key' => 'transaction_description','label' => 'Transaction Being Approved',             'type' => 'textarea','placeholder' => 'e.g. Issuance of 3,000,000 new Class A shares at USD 1.67/share to SQUAD Capital Partners for USD 5,010,000.', 'required' => true],
        ['key' => 'resolutions_passed',     'label' => 'Resolutions Passed',                    'type' => 'textarea','placeholder' => "RESOLVED: The Board approves the investment...\nRESOLVED: The CEO is authorized to execute all transaction documents...", 'required' => true],
        ['key' => 'authorized_signatories', 'label' => 'Authorized Signatories for Closing Docs', 'type' => 'textarea','placeholder' => 'Names and titles of persons authorized to sign.', 'required' => true],
        ['key' => 'chairman_name',          'label' => 'Chairman / Presiding Director Name',    'type' => 'text',  'placeholder' => 'e.g. Ahmed Hassan',                     'required' => true],
        ['key' => 'secretary_name',         'label' => 'Secretary Name',                        'type' => 'text',  'placeholder' => 'e.g. Sara Khalil',                      'required' => true],
        ['key' => 'governing_law',          'label' => 'Governing Law',                         'type' => 'text',  'placeholder' => 'e.g. Arab Republic of Egypt',           'required' => true],
    ]),
],

// ─── 16. COMPLETION CHECKLIST ────────────────────────────────────────────────
[
    'slug'        => 'completion_checklist',
    'name'        => 'Completion Checklist',
    'short_name'  => 'Completion CL',
    'category'    => 'closing',
    'icon'        => '✅',
    'description' => 'Tracks all conditions precedent and deliverables required to reach financial close.',
    'sort_order'  => 16,
    'variables'   => json_encode([
        ['key' => 'transaction_name',       'label' => 'Transaction / Deal Name',              'type' => 'text',    'placeholder' => 'e.g. SQUAD Capital → TechVenture Investment', 'required' => true],
        ['key' => 'target_company',         'label' => 'Target Company Name',                  'type' => 'text',    'placeholder' => 'e.g. TechVenture S.A.E.',                'required' => true],
        ['key' => 'investor_name',          'label' => 'Investor / Fund Name',                 'type' => 'text',    'placeholder' => 'e.g. SQUAD Capital Partners',            'required' => true],
        ['key' => 'target_closing_date',    'label' => 'Target Closing Date',                  'type' => 'date',    'placeholder' => '',                                       'required' => true],
        ['key' => 'legal_advisor_investor', 'label' => 'Legal Advisor — Investor',             'type' => 'text',    'placeholder' => 'e.g. Matouk Bassiouny & Hennawy',        'required' => false],
        ['key' => 'legal_advisor_target',   'label' => 'Legal Advisor — Target',               'type' => 'text',    'placeholder' => 'e.g. Zulficar & Partners',               'required' => false],
        ['key' => 'additional_conditions',  'label' => 'Additional / Deal-Specific Conditions','type' => 'textarea','placeholder' => 'Any CPs beyond the standard checklist.',  'required' => false],
        ['key' => 'funds_flow_coordinator', 'label' => 'Funds Flow Coordinator',               'type' => 'text',    'placeholder' => 'e.g. Sara Khalil — CFO (target)',         'required' => false],
        ['key' => 'settlement_account',     'label' => 'Settlement Bank Account',               'type' => 'textarea','placeholder' => 'Bank name, account number, IBAN, SWIFT',  'required' => false],
        ['key' => 'document_date',          'label' => 'Checklist Date',                       'type' => 'date',    'placeholder' => '',                                       'required' => true],
    ]),
],

// ─── 17. SHARE TRANSFER AGREEMENT ────────────────────────────────────────────
[
    'slug'        => 'share_transfer_agreement',
    'name'        => 'Share Transfer Agreement',
    'short_name'  => 'STA',
    'category'    => 'closing',
    'icon'        => '🔄',
    'description' => 'Agreement for secondary share purchases — transfers existing shares from seller to buyer.',
    'sort_order'  => 17,
    'variables'   => json_encode([
        ['key' => 'company_name',           'label' => 'Company Name (Shares Being Transferred)', 'type' => 'text', 'placeholder' => 'e.g. TechVenture S.A.E.',               'required' => true],
        ['key' => 'company_registration',   'label' => 'Company Registration Number',            'type' => 'text',  'placeholder' => 'e.g. 12345 Cairo Commercial Registry',  'required' => false],
        ['key' => 'transferor_name',        'label' => 'Transferor (Seller) — Full Legal Name',  'type' => 'text',  'placeholder' => 'e.g. Ahmed Hassan',                     'required' => true],
        ['key' => 'transferor_id',          'label' => 'Transferor — National ID / Passport No.','type' => 'text',  'placeholder' => 'e.g. NID: 28001010100001',              'required' => false],
        ['key' => 'transferee_name',        'label' => 'Transferee (Buyer) — Full Legal Name',   'type' => 'text',  'placeholder' => 'e.g. SQUAD Capital Partners LLC',       'required' => true],
        ['key' => 'transferee_address',     'label' => 'Transferee Registered Address',          'type' => 'textarea','placeholder' => '5 Mossadak St, Dokki, Giza, Egypt',    'required' => true],
        ['key' => 'shares_transferred',     'label' => 'Number of Shares Transferred',           'type' => 'text',  'placeholder' => 'e.g. 1,500,000 Ordinary Shares',        'required' => true],
        ['key' => 'share_class',            'label' => 'Share Class',                            'type' => 'select','options' => ['Ordinary Shares','Class A Preference Shares','Class B Ordinary','Founders Shares'], 'required' => true],
        ['key' => 'price_per_share',        'label' => 'Price Per Share',                        'type' => 'text',  'placeholder' => 'e.g. USD 1.67',                         'required' => true],
        ['key' => 'total_consideration',    'label' => 'Total Consideration (Purchase Price)',   'type' => 'text',  'placeholder' => 'e.g. USD 2,505,000',                    'required' => true],
        ['key' => 'currency',               'label' => 'Currency',                               'type' => 'select','options' => ['USD','EUR','GBP','EGP','AED','SAR'],        'required' => true],
        ['key' => 'payment_method',         'label' => 'Payment Method',                         'type' => 'select','options' => ['Wire Transfer','Cheque','Escrow','Staged Payments'], 'required' => true],
        ['key' => 'payment_deadline_days',  'label' => 'Payment Deadline (Days from Signing)',   'type' => 'number','placeholder' => '5',                                     'required' => true],
        ['key' => 'rofo_waiver',            'label' => 'Right of First Offer / Pre-emption Waived By', 'type' => 'textarea','placeholder' => 'List all existing shareholders who have waived ROFO rights (or "N/A").', 'required' => false],
        ['key' => 'rep_warranties',         'label' => 'Key Representations & Warranties',       'type' => 'textarea','placeholder' => 'Shares free of encumbrances; no pending litigation; full ownership confirmed.', 'required' => false],
        ['key' => 'transferor_signatory',   'label' => 'Transferor Signatory Name',              'type' => 'text',  'placeholder' => 'e.g. Ahmed Hassan',                     'required' => true],
        ['key' => 'transferee_signatory',   'label' => 'Transferee Signatory Name',              'type' => 'text',  'placeholder' => 'e.g. Mahmoud Youssef',                  'required' => true],
        ['key' => 'transferee_title',       'label' => 'Transferee Signatory Title',             'type' => 'text',  'placeholder' => 'e.g. Managing Partner',                 'required' => true],
        ['key' => 'governing_law',          'label' => 'Governing Law',                          'type' => 'text',  'placeholder' => 'e.g. Arab Republic of Egypt',           'required' => true],
        ['key' => 'effective_date',         'label' => 'Agreement Date',                         'type' => 'date',  'placeholder' => '',                                      'required' => true],
    ]),
],

// ─── 18. LOAN AGREEMENT / CONVERTIBLE NOTE ───────────────────────────────────
[
    'slug'        => 'loan_agreement',
    'name'        => 'Loan Agreement / Convertible Note',
    'short_name'  => 'Loan / C-Note',
    'category'    => 'closing',
    'icon'        => '💳',
    'description' => 'Agreement for debt or convertible instrument — covers principal, interest, maturity, and conversion terms.',
    'sort_order'  => 18,
    'variables'   => json_encode([
        ['key' => 'instrument_type',        'label' => 'Instrument Type',                      'type' => 'select',  'options' => ['Term Loan','Revolving Credit Facility','Convertible Note','Mezzanine Loan','Bridge Loan'], 'required' => true],
        ['key' => 'lender_name',            'label' => 'Lender Full Legal Name',               'type' => 'text',    'placeholder' => 'e.g. SQUAD Capital Partners LLC',       'required' => true],
        ['key' => 'lender_address',         'label' => 'Lender Registered Address',            'type' => 'textarea','placeholder' => '5 Mossadak St, Dokki, Giza, Egypt',     'required' => true],
        ['key' => 'borrower_name',          'label' => 'Borrower Full Legal Name',             'type' => 'text',    'placeholder' => 'e.g. TechVenture S.A.E.',               'required' => true],
        ['key' => 'borrower_address',       'label' => 'Borrower Registered Address',          'type' => 'textarea','placeholder' => '10 El Tahrir Square, Cairo, Egypt',     'required' => true],
        ['key' => 'principal_amount',       'label' => 'Principal Amount',                     'type' => 'text',    'placeholder' => 'e.g. USD 2,000,000',                    'required' => true],
        ['key' => 'currency',               'label' => 'Currency',                             'type' => 'select',  'options' => ['USD','EUR','GBP','EGP','AED','SAR'],        'required' => true],
        ['key' => 'interest_rate',          'label' => 'Interest Rate (% per annum)',           'type' => 'text',    'placeholder' => 'e.g. 12% p.a. (fixed) or SOFR + 4%',   'required' => true],
        ['key' => 'interest_type',          'label' => 'Interest Type',                        'type' => 'select',  'options' => ['Fixed','Floating (SOFR+)','PIK (Payment-in-Kind)','Zero Coupon'], 'required' => true],
        ['key' => 'maturity_date',          'label' => 'Maturity / Repayment Date',            'type' => 'date',    'placeholder' => '',                                      'required' => true],
        ['key' => 'repayment_schedule',     'label' => 'Repayment Schedule',                   'type' => 'select',  'options' => ['Bullet (lump-sum at maturity)','Monthly Amortization','Quarterly Amortization','Semi-Annual','Customized'], 'required' => true],
        ['key' => 'security_collateral',    'label' => 'Security / Collateral (if any)',       'type' => 'textarea','placeholder' => 'e.g. Pledge over company shares; personal guarantee of CEO.', 'required' => false],
        ['key' => 'conversion_terms',       'label' => 'Conversion Terms (Convertible Notes only)', 'type' => 'textarea','placeholder' => "Conversion trigger: Next equity round ≥ USD 5M\nConversion price: 20% discount to round price\nConversion cap: USD 15M pre-money valuation", 'required' => false],
        ['key' => 'use_of_proceeds',        'label' => 'Use of Proceeds',                      'type' => 'textarea','placeholder' => 'e.g. 70% working capital, 30% equipment purchase.', 'required' => true],
        ['key' => 'covenants',              'label' => 'Key Covenants',                        'type' => 'textarea','placeholder' => 'e.g. Net Debt/EBITDA ≤ 3.0x; no additional debt without consent.', 'required' => false],
        ['key' => 'events_of_default',      'label' => 'Events of Default',                    'type' => 'textarea','placeholder' => 'Missed payment, breach of covenants, insolvency, change of control.', 'required' => false],
        ['key' => 'lender_signatory',       'label' => 'Lender Signatory Name & Title',        'type' => 'text',    'placeholder' => 'e.g. Mahmoud Youssef, Managing Partner', 'required' => true],
        ['key' => 'borrower_signatory',     'label' => 'Borrower Signatory Name & Title',      'type' => 'text',    'placeholder' => 'e.g. Ahmed Hassan, CEO',                'required' => true],
        ['key' => 'governing_law',          'label' => 'Governing Law',                        'type' => 'text',    'placeholder' => 'e.g. Arab Republic of Egypt',           'required' => true],
        ['key' => 'effective_date',         'label' => 'Agreement Date',                       'type' => 'date',    'placeholder' => '',                                      'required' => true],
    ]),
],

// ─────────────────────────────────────────────────────────────────────────────
// POST-INVESTMENT
// ─────────────────────────────────────────────────────────────────────────────

// ─── 19. BOARD MEETING MINUTES TEMPLATE ──────────────────────────────────────
[
    'slug'        => 'board_meeting_minutes',
    'name'        => 'Board Meeting Minutes Template',
    'short_name'  => 'Board Minutes',
    'category'    => 'post_investment',
    'icon'        => '📝',
    'description' => 'Structured template for recording board meeting proceedings — agenda, attendees, decisions, and actions.',
    'sort_order'  => 19,
    'variables'   => json_encode([
        ['key' => 'company_name',           'label' => 'Company Name',                         'type' => 'text',    'placeholder' => 'e.g. TechVenture S.A.E.',                'required' => true],
        ['key' => 'meeting_number',         'label' => 'Meeting Number / Reference',            'type' => 'text',    'placeholder' => 'e.g. Board Meeting #8 — Q1 2025',        'required' => false],
        ['key' => 'meeting_date',           'label' => 'Meeting Date',                          'type' => 'date',    'placeholder' => '',                                       'required' => true],
        ['key' => 'meeting_time',           'label' => 'Meeting Time',                          'type' => 'text',    'placeholder' => 'e.g. 10:00 AM – 12:30 PM (Cairo time)',  'required' => false],
        ['key' => 'meeting_location',       'label' => 'Meeting Location / Platform',           'type' => 'text',    'placeholder' => 'e.g. Company HQ Boardroom / Zoom',       'required' => true],
        ['key' => 'chairman',               'label' => 'Chairman',                              'type' => 'text',    'placeholder' => 'e.g. Ahmed Hassan',                      'required' => true],
        ['key' => 'secretary',              'label' => 'Meeting Secretary',                     'type' => 'text',    'placeholder' => 'e.g. Sara Khalil',                       'required' => true],
        ['key' => 'board_members_present',  'label' => 'Board Members Present',                 'type' => 'textarea','placeholder' => "Ahmed Hassan — Chairman\nMahmoud Youssef — Investor Director\nSara Khalil — CFO & Secretary", 'required' => true],
        ['key' => 'invitees',               'label' => 'Invitees / Guests (non-board)',         'type' => 'textarea','placeholder' => 'e.g. External auditor, legal counsel.',  'required' => false],
        ['key' => 'quorum_confirmed',       'label' => 'Quorum Confirmed?',                     'type' => 'select',  'options' => ['Yes — quorum confirmed','No — waived by all members present'], 'required' => true],
        ['key' => 'agenda_items',           'label' => 'Agenda Items',                          'type' => 'textarea','placeholder' => "1. Approval of prior meeting minutes\n2. Financial performance update Q4\n3. Budget approval FY2025\n4. AOB", 'required' => true],
        ['key' => 'financial_update',       'label' => 'Financial Performance Update (summary)','type' => 'textarea','placeholder' => 'Key numbers presented: Revenue, EBITDA, Cash, vs Budget.', 'required' => false],
        ['key' => 'resolutions_passed',     'label' => 'Resolutions Passed',                    'type' => 'textarea','placeholder' => "RESOLVED: FY2025 budget approved unanimously.\nRESOLVED: CEO authorized to sign new lease agreement.", 'required' => false],
        ['key' => 'actions_agreed',         'label' => 'Action Items & Owners',                 'type' => 'textarea','placeholder' => "Action: Submit Q1 management accounts by 15 April → CFO\nAction: Present growth plan for UAE by next meeting → CEO", 'required' => false],
        ['key' => 'next_meeting_date',      'label' => 'Next Meeting Date',                     'type' => 'date',    'placeholder' => '',                                       'required' => false],
        ['key' => 'document_date',          'label' => 'Minutes Prepared Date',                 'type' => 'date',    'placeholder' => '',                                       'required' => true],
    ]),
],

// ─── 20. QUARTERLY REPORTING TEMPLATE ────────────────────────────────────────
[
    'slug'        => 'quarterly_report',
    'name'        => 'Quarterly Reporting Template',
    'short_name'  => 'Q Report',
    'category'    => 'post_investment',
    'icon'        => '📊',
    'description' => 'Standard format for portfolio company management accounts and business updates to investors.',
    'sort_order'  => 20,
    'variables'   => json_encode([
        ['key' => 'company_name',           'label' => 'Company Name',                         'type' => 'text',    'placeholder' => 'e.g. TechVenture S.A.E.',                'required' => true],
        ['key' => 'reporting_quarter',      'label' => 'Reporting Quarter',                     'type' => 'select',  'options' => ['Q1 (Jan–Mar)','Q2 (Apr–Jun)','Q3 (Jul–Sep)','Q4 (Oct–Dec)'], 'required' => true],
        ['key' => 'reporting_year',         'label' => 'Reporting Year',                        'type' => 'text',    'placeholder' => 'e.g. 2025',                             'required' => true],
        ['key' => 'report_date',            'label' => 'Report Date',                           'type' => 'date',    'placeholder' => '',                                       'required' => true],
        ['key' => 'prepared_by',            'label' => 'Prepared By',                           'type' => 'text',    'placeholder' => 'e.g. Sara Khalil, CFO',                  'required' => true],
        ['key' => 'investor_recipient',     'label' => 'Investor Recipient (Fund / Firm)',       'type' => 'text',    'placeholder' => 'e.g. SQUAD Capital Partners',            'required' => true],
        ['key' => 'executive_summary',      'label' => 'Executive Summary',                     'type' => 'textarea','placeholder' => 'Q highlights — beat/miss on revenue, key operational wins, challenges.', 'required' => true],
        ['key' => 'financial_highlights',   'label' => 'Financial Highlights (Quarter)',         'type' => 'textarea','placeholder' => "Revenue: EGP 38M (Budget: EGP 35M, +8.6%)\nEBITDA: EGP 9M (Budget: EGP 8.5M, +5.9%)\nCash: EGP 12M", 'required' => true],
        ['key' => 'ytd_performance',        'label' => 'YTD Performance vs Budget',             'type' => 'textarea','placeholder' => "YTD Revenue: EGP 108M vs Budget EGP 100M (+8%)\nYTD EBITDA: EGP 25M vs Budget EGP 23M (+8.7%)", 'required' => false],
        ['key' => 'operational_update',     'label' => 'Operational Update',                    'type' => 'textarea','placeholder' => 'Headcount, customers, product/service developments, geographic expansion.', 'required' => false],
        ['key' => 'kpi_update',             'label' => 'Key KPI Update',                        'type' => 'textarea','placeholder' => "Customer Count: 192 (Q2: 175)\nChurn Rate: 4.2%\nGross Margin: 48%", 'required' => false],
        ['key' => 'risks_and_issues',       'label' => 'Key Risks & Issues',                    'type' => 'textarea','placeholder' => 'Outstanding risks, regulatory updates, supply chain issues.', 'required' => false],
        ['key' => 'outlook',                'label' => 'Q+1 / Full Year Outlook',               'type' => 'textarea','placeholder' => 'Revised forecast if applicable; next quarter priorities.', 'required' => false],
        ['key' => 'support_needed',         'label' => 'Support Required from Investor',        'type' => 'textarea','placeholder' => 'e.g. Introductions to Gulf distributors; board approval for new credit line.', 'required' => false],
        ['key' => 'currency',               'label' => 'Reporting Currency',                    'type' => 'select',  'options' => ['EGP','USD','EUR','AED','SAR'],              'required' => true],
    ]),
],

// ─── 21. EXIT NOTICE LETTER ───────────────────────────────────────────────────
[
    'slug'        => 'exit_notice_letter',
    'name'        => 'Exit Notice Letter',
    'short_name'  => 'Exit Notice',
    'category'    => 'post_investment',
    'icon'        => '🚪',
    'description' => 'Formal notice of intent to exit or sell shares — triggers ROFO, drag-along, or tag-along rights.',
    'sort_order'  => 21,
    'variables'   => json_encode([
        ['key' => 'exiting_investor',       'label' => 'Exiting Investor Full Legal Name',      'type' => 'text',    'placeholder' => 'e.g. SQUAD Capital Partners LLC',       'required' => true],
        ['key' => 'exiting_signatory',      'label' => 'Exiting Investor Signatory Name & Title','type' => 'text',   'placeholder' => 'e.g. Mahmoud Youssef, Managing Partner', 'required' => true],
        ['key' => 'company_name',           'label' => 'Portfolio Company Name',                 'type' => 'text',    'placeholder' => 'e.g. TechVenture S.A.E.',               'required' => true],
        ['key' => 'recipient_name',         'label' => 'Recipient Name & Title',                 'type' => 'text',    'placeholder' => 'e.g. Ahmed Hassan, Chairman',            'required' => true],
        ['key' => 'shares_to_exit',         'label' => 'Shares Subject to Exit',                 'type' => 'text',    'placeholder' => 'e.g. 3,000,000 Class A Preference Shares (30% stake)', 'required' => true],
        ['key' => 'exit_route',             'label' => 'Proposed Exit Route',                    'type' => 'select',  'options' => ['Strategic Trade Sale','Secondary PE Sale','IPO','Management Buyout (MBO)','Buyback by Company','Other'], 'required' => true],
        ['key' => 'indicative_price',       'label' => 'Indicative Exit Price / Valuation',      'type' => 'text',    'placeholder' => 'e.g. USD 18M equity value (indicative)',  'required' => false],
        ['key' => 'prospective_buyer',      'label' => 'Prospective Buyer (if known)',            'type' => 'text',    'placeholder' => 'e.g. Undisclosed strategic buyer (MENA region) / Confidential', 'required' => false],
        ['key' => 'rofo_notice_period_days','label' => 'ROFO Notice Period (Days per SHA)',       'type' => 'number',  'placeholder' => '30',                                    'required' => true],
        ['key' => 'rofo_exercise_deadline', 'label' => 'ROFO Exercise Deadline Date',             'type' => 'date',    'placeholder' => '',                                      'required' => true],
        ['key' => 'drag_along_triggered',   'label' => 'Drag-Along Rights Triggered?',            'type' => 'select',  'options' => ['No','Yes — notice enclosed','Yes — to be triggered upon ROFO expiry'], 'required' => true],
        ['key' => 'sha_reference',          'label' => 'Reference SHA / Investment Agreement',    'type' => 'text',    'placeholder' => 'e.g. Shareholders Agreement dated 15 March 2022', 'required' => true],
        ['key' => 'next_steps',             'label' => 'Proposed Next Steps',                     'type' => 'textarea','placeholder' => "1. Co-investors to confirm ROFO election within 30 days\n2. Engage M&A advisor\n3. Initiate structured sale process", 'required' => false],
        ['key' => 'governing_law',          'label' => 'Governing Law',                           'type' => 'text',    'placeholder' => 'e.g. Arab Republic of Egypt',           'required' => true],
        ['key' => 'letter_date',            'label' => 'Letter Date',                             'type' => 'date',    'placeholder' => '',                                      'required' => true],
            ]),
            ],

        ];

        foreach ($templates as $tpl) {
            DB::table('doc_templates')->updateOrInsert(
                ['slug' => $tpl['slug']],
                array_merge($tpl, ['created_at' => now(), 'updated_at' => now()])
            );
        }
    }
}